// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function InitializeAppearance(arg1, arg2) {
  return window['go']['main']['App']['InitializeAppearance'](arg1, arg2);
}

export function OpenDroppedFiles(arg1) {
  return window['go']['main']['App']['OpenDroppedFiles'](arg1);
}

export function OpenWorkbook() {
  return window['go']['main']['App']['OpenWorkbook']();
}

export function OpenWorkbookPath(arg1) {
  return window['go']['main']['App']['OpenWorkbookPath'](arg1);
}

export function SelectCell(arg1) {
  return window['go']['main']['App']['SelectCell'](arg1);
}

export function SetActiveSheet(arg1) {
  return window['go']['main']['App']['SetActiveSheet'](arg1);
}

export function SetAppearanceMode(arg1) {
  return window['go']['main']['App']['SetAppearanceMode'](arg1);
}

export function SetScrollPosition(arg1, arg2) {
  return window['go']['main']['App']['SetScrollPosition'](arg1, arg2);
}

export function SetSystemTheme(arg1) {
  return window['go']['main']['App']['SetSystemTheme'](arg1);
}

export function SetZoom(arg1) {
  return window['go']['main']['App']['SetZoom'](arg1);
}

export function State() {
  return window['go']['main']['App']['State']();
}
