// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function SelectCell(arg1:string):Promise<main.AppState>;

export function SetActiveSheet(arg1:string):Promise<main.AppState>;

export function SetScrollPosition(arg1:number,arg2:number):Promise<main.AppState>;

export function SetZoom(arg1:number):Promise<main.AppState>;

export function State():Promise<main.AppState>;
