// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function InitializeAppearance(arg1:main.AppearanceMode,arg2:main.AppearanceTheme):Promise<main.AppState>;

export function OpenDroppedFiles(arg1:Array<string>):Promise<main.AppState>;

export function OpenWorkbook():Promise<main.AppState>;

export function OpenWorkbookPath(arg1:string):Promise<main.AppState>;

export function SaveWorkbook():Promise<main.AppState>;

export function SaveWorkbookAs():Promise<main.AppState>;

export function SelectCell(arg1:string):Promise<main.AppState>;

export function SetActiveSheet(arg1:string):Promise<main.AppState>;

export function SetAppearanceMode(arg1:main.AppearanceMode):Promise<main.AppState>;

export function SetCellValue(arg1:string,arg2:string,arg3:string):Promise<main.AppState>;

export function SetColumnWidth(arg1:string,arg2:number,arg3:number):Promise<main.AppState>;

export function SetRowHeight(arg1:string,arg2:number,arg3:number):Promise<main.AppState>;

export function SetScrollPosition(arg1:number,arg2:number):Promise<main.AppState>;

export function SetSystemTheme(arg1:main.AppearanceTheme):Promise<main.AppState>;

export function SetZoom(arg1:number):Promise<main.AppState>;

export function State():Promise<main.AppState>;
